version: '3'

services:
  postgres:
    image: postgres:14.6-alpine
    container_name: object-manager-db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  file-manager:
    container_name: file-manager
    build: ./fileManager
    ports:
      - "8000:8000"
    entrypoint:
      - "/venv/bin/gunicorn"
      - "-b"
      - "0.0.0.0:8000"
      - "myDjango.myDjango.wsgi"
      - "--reload"
    environment:
      - DB_Host=postgres

  file-manager-fe:
    container_name: fileManager-fe
    build: ./fileManager-fe
    ports:
      - "3000:3000"
    depends_on:
      - file-manager
