# Generated by Django 4.2.1 on 2023-05-30 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(blank=True, max_length=250)),
                ('name', models.CharField(max_length=100)),
                ('is_file', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fileManager.object')),
            ],
            options={
                'db_table': 'object',
                'unique_together': {('key', 'name')},
            },
        ),
    ]
