# Generated by Django 4.2.1 on 2023-05-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='is_file',
            field=models.BooleanField(default=False),
        ),
    ]
